### ISSUE TITLE
mat1 and mat2 shapes cannot be multiplied

### ISSUE THREAD

**Issue by jacksonjack001** [aigc-apps/CogVideoX-Fun#106]
File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/linear.py", line 117, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (27216x264 and 256x3072)

————
what's the matter？

**Comment by yunkchen** [comment]
A complete log is even better.

**Comment by jacksonjack001** [comment]
2024-12-27T19:54:05.385459 - Traceback (most recent call last):
  File "/data_ext/comfyui/ComfyUI/execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/data_ext/comfyui/ComfyUI/execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/data_ext/comfyui/ComfyUI/execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/data_ext/comfyui/ComfyUI/execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/data_ext/comfyui/ComfyUI/custom_nodes/CogVideoX-Fun/comfyui/comfyui_nodes.py", line 334, in process
    sample = pipeline(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/data_ext/comfyui/ComfyUI/custom_nodes/CogVideoX-Fun/cogvideox/pipeline/pipeline_cogvideox_inpaint.py", line 1088, in __call__
    noise_pred = self.transformer(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/data_ext/comfyui/ComfyUI/custom_nodes/CogVideoX-Fun/cogvideox/models/transformer3d.py", line 589, in forward
    hidden_states = self.patch_embed(encoder_hidden_states, hidden_states)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data_ext/comfyui/ComfyUI/custom_nodes/CogVideoX-Fun/cogvideox/models/transformer3d.py", line 147, in forward
    image_embeds = self.proj(image_embeds)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/linear.py", line 117, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (12288x264 and 256x3072)

2024-12-27T19:54:05.386062 - Prompt executed in 136.03 seconds

**Comment by njzxj** [comment]
Yes, I encountered the same problem as well. Have you solved it?
