### ISSUE TITLE
'str' object has no attribute 'resize'

### ISSUE THREAD

**Issue by realisticdreamer114514** [aigc-apps/CogVideoX-Fun#15]
I edited the sample_size in my predict_i2v.py to the dimensions I want the output to have ([384, 576]) and my 2 input images (validation_image_start, validation_image_end), and it led to this: 
```
Traceback (most recent call last):
  File "D:\CogVideoX-Fun\predict_i2v.py", line 202, in <module>
    input_video, input_video_mask, clip_image = get_image_to_video_latent(validation_image_start, validation_image_end, video_length=video_length, sample_size=sample_size)
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CogVideoX-Fun\cogvideox\utils\utils.py", line 81, in get_image_to_video_latent
    image_start = [_image_start.resize([sample_size[1], sample_size[0]]) for _image_start in image_start]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CogVideoX-Fun\cogvideox\utils\utils.py", line 81, in <listcomp>
    image_start = [_image_start.resize([sample_size[1], sample_size[0]]) for _image_start in image_start]
                   ^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'resize'
```
Should I keep the sample_size as-is ([384, 672]) regardless of my input images' aspect ratio? How can I be sure the aspect ratio of the output to be the same as the input images?

**Comment by bubbliiiing** [comment]
The file path is incorrect.
