### ISSUE TITLE
Add options for enable_model_cpu_offload

### ISSUE THREAD

**Issue by SoftologyPro** [aigc-apps/CogVideoX-Fun#28]
Using the v1 and/or v1.1 models it now takes the CogVideoX-Fun UI around 17 minutes on 4090 to create a 6 second video?!

When I use the original CogVideoX code https://github.com/THUDM/CogVideo I can speed up movie generation (down to 5 minutes for the 5b model) by adding these lines into the code.

```
pipe.enable_model_cpu_offload()
pipe.vae.enable_tiling()
```

Can you add a checkbox to use those calls with the CogVideoX-Fun UI?  That should hopefully make it much faster for local 4090?

**Comment by SoftologyPro** [comment]
Sorry, I don't know what that means.
With the original CogVideoX, I use the following basic code to make a movie.

```
pipe = CogVideoXPipeline.from_pretrained(
    "THUDM/CogVideoX-5b",
    torch_dtype=torch.bfloat16
)

pipe.enable_model_cpu_offload()
pipe.vae.enable_tiling()

video = pipe(
    prompt=prompt,
    num_videos_per_prompt=1,
    num_inference_steps=50,
    num_frames=49,
    guidance_scale=6,
    generator=torch.Generator(device="cuda").manual_seed(args2.seed),
).frames[0]
```

If I do not include the nezxt 2 lines it is much slower to generate.

```
pipe.enable_model_cpu_offload()
pipe.vae.enable_tiling()
```

I was hoping that you could add those lines into CogVideoX-Fun so it was faster.  It should speed it up from 17 minutes per movie to around 5 minutes a movie.

**Comment by bubbliiiing** [comment]
We have enabled "enable_model_cpu_offload" by default. How much time did you spend using CogVideoX-Fun?
![image](https://github.com/user-attachments/assets/acb62fa4-a417-47fe-8c95-620b1da81b15)

**Comment by SoftologyPro** [comment]
OK, I install the latest git code.
1. Start the UI.
2. Select `CogVideoX-Fun\CogVideoX-Fun\models\Diffusion_Transformer\CogVideoX-Fun-V1.1-5b-InP\` in the Pretrained model dropdown and wait for it to load.
3. Click Generate
Gives this error...
```
Update diffusion transformer done
Traceback (most recent call last):
  File "D:\CogVideoX-Fun\CogVideoX-Fun\venv\lib\site-packages\gradio\queueing.py", line 622, in process_events
    response = await route_utils.call_process_api(
  File "D:\CogVideoX-Fun\CogVideoX-Fun\venv\lib\site-packages\gradio\route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\CogVideoX-Fun\CogVideoX-Fun\venv\lib\site-packages\gradio\blocks.py", line 2012, in process_api
    inputs = await self.preprocess_data(
  File "D:\CogVideoX-Fun\CogVideoX-Fun\venv\lib\site-packages\gradio\blocks.py", line 1711, in preprocess_data
    processed_input.append(block.preprocess(inputs_cached))
  File "D:\CogVideoX-Fun\CogVideoX-Fun\venv\lib\site-packages\gradio\components\dropdown.py", line 177, in preprocess
    raise Error(
gradio.exceptions.Error: 'Value: none is not in the list of choices: []'
```
What am I missing now?

**Comment by yunkchen** [comment]
> OK, I install the latest git code.
> 
> 1. Start the UI.
> 2. Select `CogVideoX-Fun\CogVideoX-Fun\models\Diffusion_Transformer\CogVideoX-Fun-V1.1-5b-InP\` in the Pretrained model dropdown and wait for it to load.
> 3. Click Generate
>    Gives this error...
> 
> ```
> Update diffusion transformer done
> Traceback (most recent call last):
>   File "D:\CogVideoX-Fun\CogVideoX-Fun\venv\lib\site-packages\gradio\queueing.py", line 622, in process_events
>     response = await route_utils.call_process_api(
>   File "D:\CogVideoX-Fun\CogVideoX-Fun\venv\lib\site-packages\gradio\route_utils.py", line 323, in call_process_api
>     output = await app.get_blocks().process_api(
>   File "D:\CogVideoX-Fun\CogVideoX-Fun\venv\lib\site-packages\gradio\blocks.py", line 2012, in process_api
>     inputs = await self.preprocess_data(
>   File "D:\CogVideoX-Fun\CogVideoX-Fun\venv\lib\site-packages\gradio\blocks.py", line 1711, in preprocess_data
>     processed_input.append(block.preprocess(inputs_cached))
>   File "D:\CogVideoX-Fun\CogVideoX-Fun\venv\lib\site-packages\gradio\components\dropdown.py", line 177, in preprocess
>     raise Error(
> gradio.exceptions.Error: 'Value: none is not in the list of choices: []'
> ```
> 
> What am I missing now?

downgrade gradio version to 3.41.2~3.48.0

we would solve this problem in https://github.com/aigc-apps/CogVideoX-Fun/pull/41

**Comment by SoftologyPro** [comment]
OK, rolling back gradio to 3.41.2 works, but the UI shows error when the model dropdown is selected.  Even though in the background it loads the model.
When Generate is clicked it also shows error in the output area, but does continue to run in the background.
The video generation (with all defaults) still takes around 17 minutes to finish?  Should it be faster now?

**Comment by SoftologyPro** [comment]
Patching gradio to 3.48.0 fixes the error.
But it is still taking 17 minutes for the default settings on a 4090?
Was the cpu offload inplemented yet?

**Comment by bubbliiiing** [comment]
非常抱歉长久没有回应，这看起来似乎是用了共享内存导致的，理论上enable_model_cpu_offload并不会影响生成时间

**Comment by bubbliiiing** [comment]
I'm very sorry for not replying for a long time. It seems to be caused by the use of shared memory in Windows. Theoretically, enable_madel_cpu_offload will not affect the generation time
