### ISSUE TITLE
[CogVideoX-Fun](https://github.com/aigc-apps/CogVideoX-Fun) Can the trained lora, CogVideoX-Fun-V1.1-Reward-LoRAs, run on CogVideoX-5b-I2V

### ISSUE THREAD

**Issue by mrlihellohorld** [aigc-apps/CogVideoX-Fun#95]
Can the trained LoRA model, CogVideoX-Fun-V1.1-Reward-LoRAs, be used with CogVideoX-5b-I2V?

**Comment by mrlihellohorld** [comment]
lora_name = 'CogVideoX-Fun-V1.1-5b-InP-HPS2.1.safetensors'
        self.pipe.load_lora_weights(lora_path_root,weight_name=lora_name, adapter_name=adapter_name)
        Use the base model CogVideoX-5b-I2V to load lora:CogVideoX-Fun-V1.1-5b-InP-HPS2.1.safetensors.
        
        Traceback (most recent call last):
File "", line 1, in
File "/code/ace/CogVideo/smart_g_image_to_video_sobey/app/src/I2VExtensionPackage/diffusers/loaders/lora_pipeline.py", line 2513, in load_lora_weights
self.load_lora_into_transformer(
File "/code/ace/CogVideo/smart_g_image_to_video_sobey/app/src/I2VExtensionPackage/diffusers/loaders/lora_pipeline.py", line 2550, in load_lora_into_transformer
transformer.load_lora_adapter(
File "/code/ace/CogVideo/smart_g_image_to_video_sobey/app/src/I2VExtensionPackage/diffusers/loaders/peft.py", line 226, in load_lora_adapter
lora_config_kwargs = get_peft_kwargs(rank, network_alpha_dict=network_alphas, peft_state_dict=state_dict)
File "/code/ace/CogVideo/smart_g_image_to_video_sobey/app/src/I2VExtensionPackage/diffusers/utils/peft_utils.py", line 153, in get_peft_kwargs
r = lora_alpha = list(rank_dict.values())[0]
IndexError: list index out of range

**Comment by hkunzhe** [comment]
We've update CogVideoX-Fun-V1.5 and its corresponding Reward LoRAs https://huggingface.co/alibaba-pai/CogVideoX-Fun-V1.5-Reward-LoRAs.
