### ISSUE TITLE
如何设置Trainable modules

### ISSUE THREAD

**Issue by yiboz2001** [aigc-apps/CogVideoX-Fun#96]
在训练时报错如下：

```
loading annotations from metadata.json ...
data scale: 101
Trainable modules '['.']'.
[rank3]: Traceback (most recent call last):
[rank3]:   File "train_zyb.py", line 1157, in main
[rank3]:     transformer3d, optimizer, train_dataloader, lr_scheduler = accelerator.prepare(
[rank3]:   File "/home/zhangyibo/miniconda3/envs/cogvideo-fun/lib/python3.9/site-packages/accelerate/accelerator.py", line 1333, in prepare
[rank3]:     result = self._prepare_deepspeed(*args)
[rank3]:   File "/home/zhangyibo/miniconda3/envs/cogvideo-fun/lib/python3.9/site-packages/accelerate/accelerator.py", line 1773, in _prepare_deepspeed
[rank3]:     deepspeed_plugin.set_moe_leaf_modules(model)
[rank3]:   File "/home/zhangyibo/miniconda3/envs/cogvideo-fun/lib/python3.9/site-packages/accelerate/utils/dataclasses.py", line 1365, in set_moe_leaf_modules
[rank3]:     raise Exception(
[rank3]: Exception: Could not find a transformer layer class called '' to wrap in the model.
```

请问这个报错和设置Trainable modules有关吗，如何解决呢?  感谢!

**Comment by yiboz2001** [comment]
accelerate 设置错误：  deepspeed_moe_layer_cls_names: ''
